### ISSUE TITLE
安卓测试代码报错

### ISSUE THREAD

**Issue by zisheng-ai** [MudOnTire/LeancloudPushDemo#1]
![image](https://user-images.githubusercontent.com/13204332/43710905-a1994260-99a3-11e8-9492-26ffc2b750f0.png)

![image](https://user-images.githubusercontent.com/13204332/43710891-913610d8-99a3-11e8-85ca-ea1016e2f4b4.png)

**Comment by zisheng-ai** [comment]
![image](https://user-images.githubusercontent.com/13204332/43714621-2b1671c8-99b0-11e8-9cb0-87fbd52865f2.png)

![image](https://user-images.githubusercontent.com/13204332/43714607-1ffad0e0-99b0-11e8-95f6-9a1c700bd679.png)

该引的包，我都引入了

**Comment by MudOnTire** [comment]
@youngjuning 解决了吗？应该只要引用 `com.avos.avoscloud.AVOSCloud`就行了。
