### ISSUE TITLE
这个push 的地址，你是在哪找的？？

### ISSUE THREAD

**Issue by zisheng-ai** [MudOnTire/LeancloudPushDemo#2]
![image](https://user-images.githubusercontent.com/13204332/43813511-921ab8cc-9af8-11e8-9630-a3ca01c5cb50.png)

**Comment by MudOnTire** [comment]
@youngjuning 
 不好意思，刚刚才看到。在官方文档里面就有：
https://leancloud.cn/docs/android_push_guide.html#hash1393576931;

![11534216668_ pic](https://user-images.githubusercontent.com/11326927/44070028-2d8603e2-9fb4-11e8-8ed3-8b41336f00f8.jpg)

前面这8个字符是你app id的前八位：
![21534216787_ pic](https://user-images.githubusercontent.com/11326927/44070037-396d683a-9fb4-11e8-9953-f0aa1192e293.jpg)

**Comment by zisheng-ai** [comment]
Thanks Bro
